org: sidd34po
app: multilambda
service: multilamda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  function1:
    handler: index.function1
    events:
      - http:
          path: /function1

  function2:
    handler: index.function2
    events:
      - http:
          path: /function2
